#!/bin/bash
set -ex

start_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
build_command="${@:1}"
image=dukebarman/ghidra-builder

docker run \
    -it \
    -v $PWD:/files \
    -w /files \
    --user dockerbot:dockerbot \
    --rm $image \
    sh -c "$build_command"
